export const FETCH_LAUNCHPADS_REQUEST = 'FETCH_LAUNCHPADS_REQUEST'
export const FETCH_LAUNCHPADS_SUCCESS = 'FETCH_LAUNCHPADS_SUCCESS'
export const FETCH_LAUNCHPADS_FAILURE = 'FETCH_LAUNCHPADS_FAILURE'